#ifndef __MALI_OSK_CONFIG_H__
#define __MALI_OSK_CONFIG_H__

#define MALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB 16
#undef MALI_PROFILING_SKIP_PP_JOBS
#undef MALI_PROFILING_SKIP_GP_JOBS
#define MALI_ENABLE_CPU_CYCLES 0
#define MALI_STATE_TRACKING 1
#define MALI_UPPER_HALF_SCHEDULING

#endif /* __MALI_OSK_CONFIG_H__ */
